node_templates:
    app1:
            instance: app_name_1
            type: tosca.nodes.Container.Application.Docker
            properties:
                ports:
                    in_port:
                        protocol: tcp
                        target: 50000
            artifacts:
                image: 
                   file: image_name
                   repository: docker_hub
                   description: busy-box
            requirements:
                host:
                    node:  py_id
                    cpu_quota: 20000
                    relationship: HostedOn
                    bootstrap: yes