node_templates:                                        
    app1:
            instance: stress1
            type: tosca.nodes.Container.Application.Docker
            properties:
                ports:
                    in_port:
                        protocol: tcp
                        target: 50000
            artifacts:
                image: 
                   file: stress-test
                   repository: docker_hub
                   description: busy-box
            requirements:
                host:
                    node:  raspy3-A
                    cpu_quota: 20000
                    relationship: HostedOn
                    bootstrap: yes
                    status: online